// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'

// Create Virtual Routes

const TransferenciaManualLazyImport = createFileRoute('/transferencia-manual')()
const HistoricoLazyImport = createFileRoute('/historico')()
const CadastrarProdutoLazyImport = createFileRoute('/cadastrar-produto')()
const GerenciarProdutosPageLazyImport = createFileRoute(
  '/gerenciar-produtos/$page',
)()
const AlterarProdutoConvenioLazyImport = createFileRoute(
  '/alterar-produto/$convenio',
)()

// Create/Update Routes

const TransferenciaManualLazyRoute = TransferenciaManualLazyImport.update({
  path: '/transferencia-manual',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/transferencia-manual.lazy').then((d) => d.Route),
)

const HistoricoLazyRoute = HistoricoLazyImport.update({
  path: '/historico',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/historico.lazy').then((d) => d.Route))

const CadastrarProdutoLazyRoute = CadastrarProdutoLazyImport.update({
  path: '/cadastrar-produto',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/cadastrar-produto.lazy').then((d) => d.Route),
)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const GerenciarProdutosPageLazyRoute = GerenciarProdutosPageLazyImport.update({
  path: '/gerenciar-produtos/$page',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/gerenciar-produtos.$page.lazy').then((d) => d.Route),
)

const AlterarProdutoConvenioLazyRoute = AlterarProdutoConvenioLazyImport.update(
  {
    path: '/alterar-produto/$convenio',
    getParentRoute: () => rootRoute,
  } as any,
).lazy(() =>
  import('./routes/alterar-produto.$convenio.lazy').then((d) => d.Route),
)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/cadastrar-produto': {
      preLoaderRoute: typeof CadastrarProdutoLazyImport
      parentRoute: typeof rootRoute
    }
    '/historico': {
      preLoaderRoute: typeof HistoricoLazyImport
      parentRoute: typeof rootRoute
    }
    '/transferencia-manual': {
      preLoaderRoute: typeof TransferenciaManualLazyImport
      parentRoute: typeof rootRoute
    }
    '/alterar-produto/$convenio': {
      preLoaderRoute: typeof AlterarProdutoConvenioLazyImport
      parentRoute: typeof rootRoute
    }
    '/gerenciar-produtos/$page': {
      preLoaderRoute: typeof GerenciarProdutosPageLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexRoute,
  CadastrarProdutoLazyRoute,
  HistoricoLazyRoute,
  TransferenciaManualLazyRoute,
  AlterarProdutoConvenioLazyRoute,
  GerenciarProdutosPageLazyRoute,
])
